[package]
name = "mmi-parser"
version = "0.1.2"
edition = "2021"
authors = ["Nick Anthony"]
description = "A parser for MetaMap MMI output."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/UK-IPOP/mmi-parser-rs"
repository = "https://github.com/UK-IPOP/mmi-parser-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
# this effectively enable the feature `no-color` of colored when testing with
# `cargo test --feature dumb_terminal`
dumb_terminal = ["colored/no-color"]